const express=require('express')
const cors=require('cors')
const app=express()
app.use(express.urlencoded({extended:false}))
app.use(express.json())
app.use(cors())
app.use('/v1/widgets',require('./controllers/v1/widgets'))
app.get('*',(req,res)=>{
    res.status(404).send({message : 'Not Found'})
})
app.listen(3000,()=>{console.log('App is Listening on port 3k')})
